version: "3.8"

services:
  cliapp:
    build:
      context: .
      dockerfile: Dockerfile.cliapp
    volumes:
      - shared-volume:/opt/chimera/data

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "8080:80"
    volumes:
      - shared-volume:/opt/chimera/data

  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   hostname: redis-host

volumes:
  shared-volume:
